### ISSUE TITLE
Need improved in the branding section & images

### ISSUE THREAD

**Issue by iqbalmauludy** [thatplugincompany/login-designer#12]
when I try to disable branding, the logo still appears in the login area.

Last one, I think it would be more interesting if the user can add an image as background.

**Comment by richtabor** [comment]
Hey man! Do you mind posting a small screencast of the issue? I have not been able to replicate this, but I’m investigating. 👍

**Comment by richtabor** [comment]
Hi Igbal, 

I see what's going on here now. The branding logo does indeed stick when it's set to "off", though it's not resolving on the front-end, just within the Customizer. 

Give me a few more minutes to dive in and I'll have a fix pushed out this morning. 

Thanks for reporting the issue!

**Comment by richtabor** [comment]
I've just committed the fix. I should have the update out here shortly. 👍
