### ISSUE TITLE
Accreditation link obscures active links

### ISSUE THREAD

**Issue by HandyGadget** [thatplugincompany/login-designer#13]
On a small mobile window, the accreditation link/image obscures and prevents access to the password reset links and can even compromise the login button. 

[https://i.imgur.com/ekiDJCV.png](https://i.imgur.com/ekiDJCV.png)

One idea might be to provide built-in functionality to place the link precisely, rather than arbitarily letting it fall bottom right.

**Comment by richtabor** [comment]
Thanks for reporting this Terence! 🎉
I think it may be best to just hide the accreditation link/image on smaller screens.

**Comment by HandyGadget** [comment]
That makes sense as real estate is very limited on those small screens.

I accept it is highly personalised view, but even with the standard desktop presentation the bottom location right is sub-optimal.  For example ~ [https://i.imgur.com/TDPMzld.png](https://i.imgur.com/TDPMzld.png)

I have the accreditation switched off due to its location on small screens AND because it sits on top of the graphic.  I would be happy to switch it on if you are going to add positioning capability, or I will wait until development settles down a little and simply edit the CSS to relocate on bottom right.  Either way, no problem.

Great plugin Rich.

**Comment by richtabor** [comment]
Thanks for the screenshot @TerenceMilbourn - it really helps to put your feedback within context. I'll open another issue to enable positioning and see what I can do. 

Thanks for contributing to Login Designer and helping to make it the best login customizer around! If you ever need anything, feel free to hit me up! 🤜🤛
