### ISSUE TITLE
Customizer options appear too vertically thin and practically overlap

### ISSUE THREAD

**Issue by ZebulanStanphill** [thatplugincompany/login-designer#15]
In the login customizer, the various options all seem to be too thin vertically, resulting in them practically overlapping and being rather messy looking. I'm guessing this is due to some CSS issue where the height is being overridden by something.

I am using the latest versions of WordPress 4.9.4 and the Divi theme. (I've had this problem ever since I installed the plugin several months ago, but I never got around to reporting it until now.)

![selection_001](https://user-images.githubusercontent.com/19592990/37249269-0465db66-24aa-11e8-9c37-40a5a986373e.png)

**Comment by richtabor** [comment]
Hey @SuperGeniusZeb, thanks for the official report. It looks like Divi modifies the core WordPress Customizer styling quite a bit — even outside of it's own settings panels. 

I'll see what I can do, but it looks like it'll be quite an effort to negate those core style modifications. This is why it's not best practice to modify core. 😞

**Comment by ZebulanStanphill** [comment]
I see that in the latest update, you changed the stylings... it looks a lot better now! Thanks! I also went ahead and made a request on the Divi support forums to not apply customizer styles outside of their own Customizer instances, and they said they would forward my request to the design team, so perhaps the issue may be resolved on their end as well in the future so future conflicts with other plugins won't happen.

![looking-better-now](https://user-images.githubusercontent.com/19592990/37915647-a001ca9e-30df-11e8-8064-212d73be8dde.png)

I think it's safe to consider this issue resolved now. :grinning:

**Comment by richtabor** [comment]
Awesome! I tried my best to keep it decent on Divi. 👍
