### ISSUE TITLE
Redirected to the customizer for login designer once logged in

### ISSUE THREAD

**Issue by seb86** [thatplugincompany/login-designer#17]
I have come across a redirect error when using login designer for a client. It takes the user to the customizer for the login designer options once logged in. I think it is a compatibility issue with [SecuPress](https://wordpress.org/plugins/secupress/) when changing the location of the login page.

**Comment by richtabor** [comment]
Hey @seb86 is this still relevant?

**Comment by richtabor** [comment]
BTW, the Customizer is what Login Designer uses for styling :)

**Comment by seb86** [comment]
@richtabor I will have to find out what plugins were installed along side it and the options enabled to verify.

**Comment by richtabor** [comment]
@seb86 Were you able to verify this? Thanks!

**Comment by seb86** [comment]
@richtabor I have not been able to replicate the issue since WordPress 5.3 or your latest update. Perhaps the issue was resolved elsewhere but I can't say for sure. If it happens again I will make a note of it again and get back to you on the matter.

**Comment by richtabor** [comment]
Good to hear! Thanks mate!
