### ISSUE TITLE
Use new container to show background-image

### ISSUE THREAD

**Issue by hacknug** [thatplugincompany/login-designer#18]
Right now, using the body element to display a background-image leaves you with positioning controls that don't do exactly what you (or at least I) would expect from them. `center center` should center the image on the right area not the whole body as it makes the left-side with the form overlap a part of the image.

This change would only require adding an extra element with the background settings that now are getting applied to the body itself.

**Comment by richtabor** [comment]
Hi @hacknug 

I think the issue is that when **Size** is set to "_Cover_", the **Position** controls don't take affect, as `background-size: cover;` overrides the image positioning (naturally). 

I'm thinking I should set a conditional view, so that the Position control only displays if the Size selector is not set to cover. What do you think?

**Comment by hacknug** [comment]
I was talking about positioning with contain (but the same I tried to describe would apply to cover).

Here's a short video showing how the background image is applied to the `body` and inside this you have the login form: https://streamable.com/yohxu

What I would expect here is to have two different sections inside the body: one for the login form and one for my background. This would let me position my image inside that same section without the form covering a part of it.

Hope this makes it clearer.

**Comment by richtabor** [comment]
I think it'd be a good idea to also set the **Size** value to "auto" if Repeat is set to a tiled option. This way, you won't end up in a position where you want it tiled, but have to set another option as well to get it.

**Comment by richtabor** [comment]
Oh I see now!

**Comment by richtabor** [comment]
@hacknug Want to try out the adjustments? I've bundled up the plugin [here](http://cl.ly/ro6I) which you may download and run. Let me know if that works for you (and if it solves the issue) when you have a minute. 👍

**Comment by hacknug** [comment]
Looks good to me!
