### ISSUE TITLE
login_headertitle is deprecated since WP 5.2.0

### ISSUE THREAD

**Issue by brendanmullan** [thatplugincompany/login-designer#21]
As of WP 5.2.0 login_headertitle is deprecated. Need to update to login_headertext

Notice: login_headertitle is deprecated since version 5.2.0! Use login_headertext instead. Usage of the title attribute on the login logo is not recommended for accessibility reasons. Use the link text instead. in /home/xxxxxx/public_html/wp-includes/functions.php on line 4711

Thanks :-)

**Comment by richtabor** [comment]
Good find @brendanmullan - I'll get this fixed. 👌

**Comment by brendanmullan** [comment]
Thanks @richtabor :-)

**Comment by richtabor** [comment]
Merged via #22
