### ISSUE TITLE
ISBAT save, import and export templates

### ISSUE THREAD

**Issue by Twanneman** [thatplugincompany/login-designer#24]
@richtabor It would be awesome if I could save, import or export templates for Login Designer settings and options. There is an option screen for templates, how can I add custom templates to this overview? In this topic https://github.com/thatplugincompany/login-designer/issues/5 you replied that you created a Pro add-on for this functionality but I can't find it anywhere online. Please advise.

**Comment by richtabor** [comment]
Hey @Twanneman, I had but I have not released it. I need to review it and see if it still works (that was quite a bit ago). 👍
