### ISSUE TITLE
Customizer does not show icons to edit (Latest WP Update)

### ISSUE THREAD

**Issue by josep0101** [thatplugincompany/login-designer#25]
Login Designer WP plugin latest version + WP latest version.

Customization icon at the WP customizer for the Login Designer dissappeared, you can only change the theme, but you can't edit the background or other options that were at the right side of the window, it happened since the last WP update, I've also updated the plugin.

**Comment by richtabor** [comment]
Hey @josep0101, are you still seeing this in WordPress 5.3?

**Comment by richtabor** [comment]
Closing as I'm not able to replicate with WP 5.3.
