### ISSUE TITLE
Template 02/03 Form Background Issues

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/login-designer#3]
Essentially, the form backgrounds of these two templates is hardcoded to be transparent (for if the user has an image background), but some folks still want a background over the image. 

Here's the [WordPress.org Topic](https://wordpress.org/support/topic/form-background-issue/#post-9763866) for reference and [the url](http://www.wearestream.com/wp-login.php) the user has reported.

**Comment by richtabor** [comment]
What may work is if we check to see if a background color is set. If so, then use it — if not, then fallback to transparent (instead of the global default).

**Comment by brendanmullan** [comment]
Is there a way to edit the color picker to include a transparency option and let the user control it? Something like this:
![image](https://user-images.githubusercontent.com/4569153/34019644-e15b4fea-e127-11e7-96d4-e28fd10960d9.png)

**Comment by richtabor** [comment]
I looked into adding a custom control that does RGBA as well, though it was kind of "hacky" and didn't work well with live previewing very well. 

I think I may try having an option to disable the background entirely, instead of forcing it per template. What do you think of that?

**Comment by richtabor** [comment]
I just worked on adding a transparency toggle and I think it's a suitable solution.  <img width="497" alt="screen shot 2017-12-15 at 7 45 38 am" src="https://user-images.githubusercontent.com/1813435/34042725-00be25e4-e16c-11e7-947b-f1b8fbe38865.png">

**Comment by brendanmullan** [comment]
How difficult would it be to change the transparency option to a slider 0-100% ? Would be nice to be able to control it like that. P.S. This is the nicest login styler out there, I've used quite a few and just removed them all from my sites to swap this in! Awesome job and support!

**Comment by richtabor** [comment]
That's a good idea, though I do foresee an issue with the templates that also style the #login div behind the form (the side by side Template 01). Maybe a solution would be to force a transparent background on the form element, if the slider has a value other than 0? 

It'll a bit tricky to implement, though I do think it's a neat idea. 

<img width="1127" alt="screen shot 2017-12-15 at 7 52 11 am" src="https://user-images.githubusercontent.com/1813435/34042931-e157c786-e16c-11e7-996e-47ec7271bcd9.png">

**Comment by richtabor** [comment]
I'm going to close this issue and open a new enhancement to try and figure out how to implement a transparency slider for a future update. The on/off toggle will be sufficient in solving the issues some people are currently facing, though I do want to investigate the slider functionality more.

Thanks again!

**Comment by brendanmullan** [comment]
Yeah that's a good call, always better to make something work then make it work better than waiting until it's perfect!

Will install the latest version soon as you have it available 👍
