### ISSUE TITLE
Use a range control, instead of an on/off toggle, for the form background transparency 

### ISSUE THREAD

**Issue by richtabor** [thatplugincompany/login-designer#6]
It's been suggested to change the transparency toggle (pictured below) to a range control (0-100%). 
<img width="497" alt="screen shot 2017-12-15 at 7 45 38 am" src="https://user-images.githubusercontent.com/1813435/34043190-e57d5d52-e16d-11e7-8cf4-ae851edd7cd1.png">

It's a good idea, though I do foresee an issue with the templates that also style the #login div behind the form (the side by side Template 01). Maybe a solution would be to force a transparent background on the form element, if the slider has a value other than 0?

Here's what would currently happen if the transparency is anything but 0 or 100%.
<img width="1127" alt="screen shot 2017-12-15 at 7 52 11 am" src="https://user-images.githubusercontent.com/1813435/34043214-0b11f654-e16e-11e7-9caf-55ec81d2e853.png">

**Comment by HardeepAsrani** [comment]
This should come handy for this: http://braadmartin.com/alpha-color-picker-control-for-the-wordpress-customizer/
